server:
  port: 8080

spring:
  application:
    name: star-finance-backend
  
  data:
    mongodb:
      uri: mongodb+srv://iamchandrakanth1618:C1234@cluster0.n43m3rj.mongodb.net/starfinance?retryWrites=true&w=majority&appName=Cluster0
      database: starfinance
  
  security:
    jwt:
      secret: your-secret-key-here-make-it-long-and-secure-in-production
      expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.starfinance: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# CORS configuration for frontend
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*" 